GET http://localhost:8000   

### API Create user
POST http://localhost:8000/user/registration
Content-Type: application/json

{
    "fullname": "El Setiyawan Dua",
    "email": "el_dua@gmail.com",
    "password": "123456"
}


### 
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "el@gmail.com",
    "password": "123456"
}
