GET http://localhost:8000   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJFbCBTZXRpeWF3YW4iLCJlbWFpbCI6ImVsQGdtYWlsLmNvbSIsImlhdCI6MTY1OTYxNzIyNCwiZXhwIjoxNjU5NzAzNjI0fQ.lB2iHE_Z4NLF4BByHNFX9kn4h0dV54Z-oGg7IpGYCR4

### API Create user
POST http://localhost:8000/user/registration
Content-Type: application/json

{
    "email": "el_dua@gmail.com",
    "password": "Password@123!"
}


### 
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "el@gmail.com",
    "password": ""
}


### Edit nama user
POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJFbCBTZXRpeWF3YW4iLCJlbWFpbCI6ImVsQGdtYWlsLmNvbSIsImlhdCI6MTY1OTYxNzIyNCwiZXhwIjoxNjU5NzAzNjI0fQ.lB2iHE_Z4NLF4BByHNFX9kn4h0dV54Z-oGg7IpGYCR4

{
    "title": "Judulnya",
    "image": "gambarnya",
    "body": "bodynya"
}