stages: 
  - test
  - deploy

test: 
  stage : test
  image : node:latest
  script: 
    - npm install
    - npm run test

test2: 
  stage : test
  image : node:latest
  script: 
    - npm install
    - npm run test


deploy : 
  stage : deploy
  script : 
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY

